[pytest]
addopts = -v --tb=short --capture=sys --alluredir=reports/allure
log_cli = true
log_cli_level = INFO
log_file = reports/test_log.log
log_file_level = INFO
markers =
    regression: Mark test as regression
    smoke: Mark test as smoke test
    sanity: Mark test as sanity test
    mobile: Mark test as mobile test
    web: Mark test as web test
